#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
#  добавил это
#    composer install
#    cd /var/www/html
#    php artisan key:gen --ansi
#  	php artisan migrate
#	  php artisan db:seed
##	  php artisan schedule:run &
#	 до сюда
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

fi

